version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./src:/srv/src
      - ./node_modules:/srv/src/node_modules # https://zenn.dev/szn/articles/nuxt-3-with-docker-compose
      - ./.nuxt:/srv/src/.nuxt
      - ./.output:/srv/src/.output
    working_dir: "/srv"
    ports:
      - "3000:3000"
      - "4000:3000" # ws
      - "24678:24678" # HMR
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true
    platform: linux/arm64/v8
    command: [ "pnpm", "dev" ]
