FROM node:18.16.0-alpine

WORKDIR /srv

RUN apk update --no-cache && \
    npm i -g pnpm

COPY package.json pnpm-lock.yaml .npmrc ./
COPY nuxt.config.ts tailwind.config.js postcss.config.js tsconfig.json ./
COPY .eslintrc .prettierrc ./
COPY src ./src

RUN pnpm i && \
    pnpm build

EXPOSE 3000

CMD [ "pnpm", "dev" ]